"""Generate the paper's four figures from the benchmark results.

Inputs:  results/benchmark.csv (per-game metrics)
         results/benchmark_rows.json (per-ply bit trajectories; generated by
           INCLUDE_ROWS=1 .venv/bin/python benchmark.py full)
Outputs: paper/figs/{bpm_trajectory,bpm_vs_ply,bps_vs_ply,encoding_flow_diagram}.png

The committed PNGs are the artifact of record. Regenerating them needs the
per-ply trajectories, which are too large to commit, so the benchmark has to be
re-run with INCLUDE_ROWS=1 first.
"""

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

ROOT = Path(__file__).resolve().parent
# The paper is the only consumer of these, so they live next to paper.tex
# rather than being duplicated into results/ as well.
FIGS = ROOT / "paper" / "figs"
FIGS.mkdir(parents=True, exist_ok=True)
ROWS = ROOT / "results" / "benchmark_rows.json"

BASE = "arm1_integer_baseline"
PLAIN = "arm2_arithmetic_plain"
STEER = "arm3_arithmetic_steered"


def trajectories(arm):
    """Per-ply cumulative-bit curves for one arm."""
    if not ROWS.exists():
        raise SystemExit(
            f"missing {ROWS.relative_to(ROOT)}\n"
            "Per-ply trajectories are not committed (too large). Regenerate with:\n"
            "  INCLUDE_ROWS=1 .venv/bin/python benchmark.py full 1000\n"
            "  .venv/bin/python make_figures.py"
        )
    rows = json.loads(ROWS.read_text())["rows"]
    return [r["trajectory"] for r in rows[arm] if r.get("trajectory")]


def mean_curve(trajs, fn):
    """Average fn(traj) over games at each ply t (games still active at t)."""
    maxlen = max(len(t) for t in trajs)
    sums, counts = [0.0] * maxlen, [0] * maxlen
    for t in trajs:
        for i, v in enumerate(fn(t)):
            sums[i] += v
            counts[i] += 1
    return [s / c if c else float("nan") for s, c in zip(sums, counts)]


def cum_bpm_curve(trajs):
    """Average BPM (cumulative bits / ply) at each ply t, t = 1..30."""
    maxlen = max(len(t) for t in trajs)
    sums, counts = [0.0] * maxlen, [0] * maxlen
    for t in trajs:
        for i, v in enumerate(t):
            sums[i] += (v / (i + 1))
            counts[i] += 1
    return [s / c if c else float("nan") for s, c in zip(sums, counts)]


def per_ply_bits_curve(trajs):
    """Mean bits emitted per ply across games still active at each ply."""
    return mean_curve(trajs, lambda t: [t[0]] + [t[i] - t[i - 1] for i in range(1, len(t))])


def style_axis(ax):
    ax.grid(True, alpha=0.3)
    ax.set_xlabel("Ply")
    ax.ticklabel_format(style="plain")


def fig_bpm_trajectory():
    plt.figure(figsize=(7, 4.4))
    for arm, label, ls, color in [
        (BASE, "Integer-truncation baseline", "-", "tab:blue"),
        (STEER, "True arithmetic + steering", "--", "tab:red"),
    ]:
        ys = cum_bpm_curve(trajectories(arm))[:30]
        plt.plot(range(1, 31), ys, ls, color=color, label=label, linewidth=2)
    plt.ylabel("Average Bits-Per-Move (cumulative)")
    plt.title("Average BPM over the first 30 plies")
    plt.legend()
    style_axis(plt.gca())
    plt.tight_layout()
    plt.savefig(FIGS / "bpm_trajectory.png", dpi=200)
    plt.close()


def fig_bpm_vs_ply():
    plt.figure(figsize=(7, 4.4))
    for arm, label, ls, color in [
        (BASE, "Integer-truncation baseline", "-", "tab:blue"),
        (STEER, "True arithmetic + steering", "--", "tab:red"),
    ]:
        ys = per_ply_bits_curve(trajectories(arm))
        plt.plot(range(1, len(ys) + 1), ys, ls, color=color, label=label, linewidth=1.6)
    plt.ylabel("Bits emitted per ply (mean)")
    plt.title("Bits emitted per ply across the whole game")
    plt.legend()
    ax = plt.gca()
    style_axis(ax)
    ax.set_ylim(bottom=0)
    plt.tight_layout()
    plt.savefig(FIGS / "bpm_vs_ply.png", dpi=200)
    plt.close()


def fig_bps_vs_ply():
    """Same data as the paper's 4th figure: baseline (blue) vs steering (orange)."""
    plt.figure(figsize=(7, 4.4))
    for arm, label, color in [
        (BASE, "Baseline (integer truncation)", "tab:blue"),
        (STEER, "Steering-enabled true arithmetic coder", "tab:orange"),
    ]:
        ys = per_ply_bits_curve(trajectories(arm))
        plt.plot(range(1, len(ys) + 1), ys, color=color, label=label, linewidth=1.6)
    plt.ylabel("Bits per move (mean)")
    plt.title("Bits per move as a function of ply")
    plt.legend()
    ax = plt.gca()
    style_axis(ax)
    ax.set_ylim(bottom=0)
    plt.tight_layout()
    plt.savefig(FIGS / "bps_vs_ply.png", dpi=200)
    plt.close()


def fig_flow_diagram():
    steps = [
        ("Legal move enumeration\n$\\mathcal{M}(s_t)$ via python-chess", "tab:blue"),
        ("Probability / weight construction\n(uniform weights $p_t(m)$)", "tab:blue"),
        ("Steering bias (optional)\npawn pushes: weight $1+\\beta$, plies $<W$", "tab:orange"),
        ("Interval subdivision\n$[L_t,H_t)\\to\\{[L_{t,m},H_{t,m})\\}$", "tab:blue"),
        ("Move selection\nbucket containing $p=P/Q$", "tab:blue"),
        ("Interval update\n$[L_t,H_t)\\leftarrow[L_{t,m_t},H_{t,m_t})$", "tab:blue"),
        ("Renormalize\nemit fractional bits", "tab:green"),
    ]
    fig, ax = plt.subplots(figsize=(4.6, 8.2))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, len(steps) * 2 + 1)
    ax.axis("off")
    y = len(steps) * 2
    centers = []
    for text, color in steps:
        box = FancyBboxPatch((1.2, y - 1.1), 7.6, 1.7,
                             boxstyle="round,pad=0.12,rounding_size=0.25",
                             linewidth=1.4, edgecolor=color, facecolor="#f7f9fc")
        ax.add_patch(box)
        ax.text(5.0, y - 0.25, text, ha="center", va="center", fontsize=9.5)
        centers.append(y - 0.25)
        y -= 2
    for i in range(len(steps) - 1):
        ax.add_patch(FancyArrowPatch((5.0, centers[i + 1] + 1.05), (5.0, centers[i] - 1.05),
                                     arrowstyle="-|>", mutation_scale=16, linewidth=1.4,
                                     color="0.25"))
    ax.text(5.0, 0.15, "Decoder mirrors the pipeline: replays the moves, re-derives the weighted\n"
                       "lists and interval updates, and emits the payload bits during renormalization.",
            fontsize=8.5, color="0.35", ha="center", va="bottom")
    plt.title("Encoding pipeline", fontsize=12)
    plt.tight_layout()
    plt.savefig(FIGS / "encoding_flow_diagram.png", dpi=200)
    plt.close()


if __name__ == "__main__":
    fig_bpm_trajectory()
    fig_bpm_vs_ply()
    fig_bps_vs_ply()
    fig_flow_diagram()
    print(f"Figures written to {FIGS}")
